server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE  # lb:// Load Balanced URI,   Use load balancer, Resolve service via registry, Choose an instance
          predicates:
            - Path=/users/**

        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**

# Springdoc API Gateway aggregation
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: http://localhost:9002/v3/api-docs
      - name: department-service
        url: http://localhost:9001/v3/api-docs

  api-docs:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true   # ensures proper registration