server:
  port: 9002
management:
  endpoints:
    web:
      exposure:
        include: health,info  # Expose only health and info endpoints
  endpoint:
    info:
      enabled: true  # Make sure /actuator/info is enabled
spring:
  cloud:
    config:
      enabled: false
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true   # ensures proper registration
